services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: app_db
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: laravel_frontend
    restart: always
    depends_on:
      - backend
    volumes:
      - ./frontend:/var/www/html
    environment:
      APP_URL: http://localhost
      API_URL: http://backend:8080
    networks:
      app_network:

  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: always
    depends_on:
      - frontend
    ports:
      - "8000:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80      
    networks:
      app_network:

volumes:
  mysql_data:

networks:
  app_network: